try{
  throw Error('error things');
}
  catch(e){
    console.log(e);
  }



